package br.com.sussmartcare.queue.application; import br.com.sussmartcare.queue.domain.*; import br.com.sussmartcare.queue.infrastructure.outbox.EventOutbox; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class QueueApplicationService {private final QueueEntryRepository repo;private final EventOutbox outbox;private final WaitTimeEstimator estimator;public QueueApplicationService(QueueEntryRepository r,EventOutbox o,WaitTimeEstimator e){repo=r;outbox=o;estimator=e;}
 @Transactional public QueueEntry enter(UUID visit,UUID facility,String priority){if(repo.findByVisitId(visit).isPresent())throw new IllegalStateException("Visita já está na fila");var q=repo.save(new QueueEntry(visit,facility,priority));outbox.append("patient-queued",visit.toString(),state(q));publishFacilityView(facility);return q;} @Transactional public QueueEntry enterIfAbsent(UUID visit,UUID facility,String priority){return repo.findByVisitId(visit).orElseGet(()->enter(visit,facility,priority));} public QueueEntry get(UUID id){return repo.findById(id).orElseThrow(()->new IllegalArgumentException("Entrada de fila não encontrada"));} public QueueEntry getByVisit(UUID visitId){return repo.findByVisitId(visitId).orElseThrow(()->new IllegalArgumentException("Entrada de fila ainda não disponível para a visita"));}
 @Transactional public QueueEntry leave(UUID id,long expected,long grace){var q=get(id);q.updatePresence(PresenceState.OUTSIDE_FACILITY);q.requestReturn(Duration.ofMinutes(expected),Duration.ofMinutes(grace));repo.save(q);outbox.append("queue-return-required",q.getVisitId().toString(),state(q));publishFacilityView(q.getFacilityId());return q;}
 @Transactional public QueueEntry returned(UUID id){var q=get(id);q.returned();repo.save(q);outbox.append("patient-returned-to-queue",q.getVisitId().toString(),state(q));publishFacilityView(q.getFacilityId());return q;} @Transactional public QueueEntry call(UUID id){var q=get(id);q.call();repo.save(q);outbox.append("patient-called",q.getVisitId().toString(),state(q));publishFacilityView(q.getFacilityId());return q;}
 @Transactional public void presence(UUID visit,PresenceState state){repo.findByVisitId(visit).ifPresent(q->{q.updatePresence(state);if(state==PresenceState.INSIDE_FACILITY&&(q.getStatus()==QueueEntryStatus.RETURN_REQUIRED||q.getStatus()==QueueEntryStatus.GRACE_PERIOD||q.getStatus()==QueueEntryStatus.MISSED_CALL))q.returned();repo.save(q);outbox.append("queue-entry-state-changed",visit.toString(),state(q));publishFacilityView(q.getFacilityId());});}
 @Transactional public void evaluateReturnPolicies(int positionThreshold,long returnMinutes,long graceMinutes){for(var q:repo.findByPresenceAndStatus(PresenceState.OUTSIDE_FACILITY,QueueEntryStatus.WAITING)){var position=view(q.getFacilityId()).stream().filter(v->v.visitId().equals(q.getVisitId())).findFirst().map(QueueView::estimatedPosition).orElse(Integer.MAX_VALUE);if(position<=positionThreshold){q.requestReturn(Duration.ofMinutes(returnMinutes),Duration.ofMinutes(graceMinutes));repo.save(q);outbox.append("queue-return-required",q.getVisitId().toString(),state(q));publishFacilityView(q.getFacilityId());}}for(var status:List.of(QueueEntryStatus.RETURN_REQUIRED,QueueEntryStatus.GRACE_PERIOD)){for(var q:repo.findByPresenceAndStatus(PresenceState.OUTSIDE_FACILITY,status)){var before=q.getStatus();q.evaluateDeadline(Instant.now());if(before!=q.getStatus()){repo.save(q);outbox.append("queue-entry-state-changed",q.getVisitId().toString(),state(q));publishFacilityView(q.getFacilityId());}}}}
 public List<QueueView> view(UUID facility){var list=repo.findByFacilityId(facility).stream().filter(e->e.getStatus()==QueueEntryStatus.WAITING||e.getStatus()==QueueEntryStatus.RETURN_REQUIRED||e.getStatus()==QueueEntryStatus.GRACE_PERIOD).sorted(Comparator.comparingInt((QueueEntry e)->rank(e.getClinicalPriority())).thenComparing(QueueEntry::getEnteredAt)).toList();var out=new ArrayList<QueueView>();for(int i=0;i<list.size();i++){var e=list.get(i);out.add(new QueueView(e.getVisitId(),e.getDisplayCode(),i+1,estimator.estimateMinutes(i+1),e.getClinicalPriority(),e.getPresence().name(),e.getStatus().name()));}return out;}
 private void publishFacilityView(UUID facility){for(var v:view(facility))outbox.append("queue-position-estimated",v.visitId().toString(),new QueuePositionEstimated(v.visitId(),v.displayCode(),facility,v.estimatedPosition(),v.estimatedMinutes(),v.clinicalPriority(),v.presence(),v.status(),Instant.now()));}
 private QueueStateChanged state(QueueEntry q){return new QueueStateChanged(q.getVisitId(),q.getDisplayCode(),q.getFacilityId(),q.getClinicalPriority(),q.getPresence().name(),q.getStatus().name(),q.getExpectedReturnAt(),q.getGraceUntil(),Instant.now());} private int rank(String p){return switch(p){case "EMERGENCY"->0;case "HIGH"->1;case "MEDIUM"->2;default->3;};}
 public List<QueuePublicView> publicView(UUID facility){return view(facility).stream().map(v->new QueuePublicView(v.displayCode(),v.estimatedPosition(),v.estimatedMinutes(),v.status())).toList();} public WaitTimeEstimator.FacilityEstimate facilityEstimate(UUID facility){return estimator.aggregate(view(facility).size());} public record QueueView(UUID visitId,String displayCode,int estimatedPosition,int estimatedMinutes,String clinicalPriority,String presence,String status){} public record QueuePublicView(String displayCode,int estimatedPosition,int estimatedMinutes,String status){} public record QueuePositionEstimated(UUID visitId,String displayCode,UUID facilityId,int estimatedPosition,int estimatedMinutes,String clinicalPriority,String presence,String status,Instant updatedAt){} public record QueueStateChanged(UUID visitId,String displayCode,UUID facilityId,String clinicalPriority,String presence,String status,Instant expectedReturnAt,Instant graceUntil,Instant updatedAt){}
}
