flowchart LR
  PAT[Paciente / Responsável]
  STAFF[Recepção / Profissional]
  KIOSK[Totem / Telão]
  AMB[Equipe de Ambulância]
  DEV[Dispositivo / Gateway IoT]
  KC[Keycloak]
  MQTT[(MQTT Broker)]

  GW[API Gateway]
  CORE[SUS Smart Care\n12 aplicações]
  K[(Kafka)]
  PG[(PostgreSQL)]
  REDIS[(Redis)]
  OBS[Prometheus / Tempo / Grafana]

  PAT --> GW
  STAFF --> GW
  KIOSK --> GW
  AMB --> GW
  GW --> CORE
  GW --> KC

  DEV -->|MQTT QoS 1| MQTT
  MQTT --> CORE

  CORE <--> K
  CORE --> PG
  CORE --> REDIS
  CORE --> OBS

  CORE --> KIOSK
