package br.com.sussmartcare.notification.infrastructure;
import br.com.sussmartcare.notification.application.NotificationApplicationService; import com.fasterxml.jackson.databind.*; import java.util.*; import org.springframework.kafka.annotation.KafkaListener; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;
@Component public class NotificationEventConsumer {private final ObjectMapper mapper;private final ProcessedEventRepository processed;private final VisitPatientLinkRepository links;private final PendingVisitNotificationRepository pending;private final NotificationApplicationService app;public NotificationEventConsumer(ObjectMapper m,ProcessedEventRepository p,VisitPatientLinkRepository l,PendingVisitNotificationRepository pn,NotificationApplicationService a){mapper=m;processed=p;links=l;pending=pn;app=a;}
 private Envelope envelope(String raw)throws Exception{var e=mapper.readTree(raw);UUID id=UUID.fromString(e.path("eventId").asText());if(processed.existsById(id))return null;return new Envelope(id,e.path("data"));}
 @KafkaListener(topics="pre-visit-created",groupId="notification-visit-map")@Transactional public void visit(String raw)throws Exception{var e=envelope(raw);if(e==null)return;var d=e.data();UUID visit=UUID.fromString(d.path("visitId").asText());UUID patient=UUID.fromString(d.path("patientId").asText());links.save(new VisitPatientLink(visit,patient));for(var p:pending.findByVisitIdOrderByCreatedAtAsc(visit)){app.sendAuto(patient,visit,p.getType(),p.getMessage());pending.delete(p);}processed.save(new ProcessedEvent(e.eventId(),"notification-visit-map"));}
 @KafkaListener(topics="patient-records-merged",groupId="notification-patient-merge")@Transactional public void merge(String raw)throws Exception{var e=envelope(raw);if(e==null)return;var d=e.data();UUID source=UUID.fromString(d.path("sourcePatientId").asText());UUID target=UUID.fromString(d.path("canonicalPatientId").asText());for(var link:links.findByPatientId(source)){link.reassignPatient(target);links.save(link);}processed.save(new ProcessedEvent(e.eventId(),"notification-patient-merge"));}
 @KafkaListener(topics="queue-return-required",groupId="notification-return")@Transactional public void returnRequired(String raw)throws Exception{var e=envelope(raw);if(e==null)return;var d=e.data();UUID visit=UUID.fromString(d.path("visitId").asText());String message="Senha "+d.path("displayCode").asText("")+": aproxime-se da unidade; sua chamada está próxima. Consulte a estimativa atual.";dispatchOrPend(e.eventId(),visit,"RETURN_REQUIRED",message);processed.save(new ProcessedEvent(e.eventId(),"notification-return"));}
 @KafkaListener(topics="patient-called",groupId="notification-called")@Transactional public void called(String raw)throws Exception{var e=envelope(raw);if(e==null)return;var d=e.data();UUID visit=UUID.fromString(d.path("visitId").asText());String message="Senha "+d.path("displayCode").asText("")+": seu atendimento foi chamado. Dirija-se ao ponto indicado pela unidade.";dispatchOrPend(e.eventId(),visit,"PATIENT_CALLED",message);processed.save(new ProcessedEvent(e.eventId(),"notification-called"));}
 @KafkaListener(topics="pre-arrival-alert-created",groupId="notification-prearrival")@Transactional public void prearrival(String raw)throws Exception{var e=envelope(raw);if(e==null)return;var d=e.data();UUID patient=UUID.fromString(d.path("patientId").asText());app.send(patient,null,"PRE_ARRIVAL_ALERT","STAFF_CONSOLE","Paciente pré-hospitalar a caminho: risco="+d.path("riskLevel").asText()+" ETA="+d.path("eta").asText());processed.save(new ProcessedEvent(e.eventId(),"notification-prearrival"));}
 private void dispatchOrPend(UUID eventId,UUID visit,String type,String message){var link=links.findById(visit);if(link.isPresent())app.sendAuto(link.get().getPatientId(),visit,type,message);else pending.save(new PendingVisitNotification(eventId,visit,type,message));}
 private record Envelope(UUID eventId,JsonNode data){}
}
