package br.com.sussmartcare.triage.application;
import br.com.sussmartcare.triage.domain.*; import br.com.sussmartcare.triage.infrastructure.outbox.EventOutbox; import br.com.sussmartcare.triage.infrastructure.projection.TriageObservationRepository; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class TriageApplicationService {private final TriageRepository repo;private final EventOutbox outbox;private final RiskAssessmentPort ai;private final TriageObservationRepository observations;public TriageApplicationService(TriageRepository r,EventOutbox o,RiskAssessmentPort ai,TriageObservationRepository obs){repo=r;outbox=o;this.ai=ai;observations=obs;}
 @Transactional public Triage start(UUID visitId){if(repo.findByVisitId(visitId).isPresent())throw new IllegalStateException("Triagem já existe para a visita");var t=Triage.start(visitId);repo.save(t);outbox.append("triage-started",t.getId().toString(),new TriageStarted(t.getId(),visitId,t.getStartedAt()));return t;} @Transactional public Triage startIfAbsent(UUID visitId){return repo.findByVisitId(visitId).orElseGet(()->start(visitId));} public Triage get(UUID id){return repo.findById(id).orElseThrow(()->new IllegalArgumentException("Triagem não encontrada"));} public Triage getByVisit(UUID visitId){return repo.findByVisitId(visitId).orElseThrow(()->new IllegalArgumentException("Triagem ainda não disponível para a visita"));}
 @Transactional public Triage assess(UUID id,ClinicalPriority p,double c,String reasoning){var t=get(id);t.assessment(p,c,reasoning,"manual-demo","1.0");repo.save(t);publishAssessment(t);return t;}
 @Transactional public Triage assessWithAi(UUID id){var t=get(id);var input=observations.findTop50ByVisitIdOrderByMeasuredAtDesc(t.getVisitId()).stream().map(o->new RiskAssessmentPort.Observation(o.getType(),o.getValue(),o.getUnit(),o.getMeasuredAt())).toList();var result=ai.assess(new RiskAssessmentPort.RiskAssessmentRequest(t.getId(),t.getVisitId(),input));t.assessment(result.recommendation(),result.confidence(),result.reasoning(),result.modelName(),result.modelVersion());repo.save(t);publishAssessment(t);return t;}
 private void publishAssessment(Triage t){outbox.append("triage-assessment-generated",t.getId().toString(),new AssessmentGenerated(t.getId(),t.getVisitId(),t.getAiRecommendation(),t.getAiConfidence(),t.getAiReasoning(),t.getAiModelName(),t.getAiModelVersion()));}
 @Transactional public Triage confirm(UUID id,ClinicalPriority p,UUID professional){var t=get(id);t.confirm(p,professional);repo.save(t);outbox.append("clinical-priority-confirmed",t.getVisitId().toString(),new PriorityConfirmed(t.getVisitId(),p,professional,t.getDecidedAt()));return t;}
 public record TriageStarted(UUID triageId,UUID visitId,Instant startedAt){} public record AssessmentGenerated(UUID triageId,UUID visitId,ClinicalPriority recommendation,Double confidence,String reasoning,String modelName,String modelVersion){} public record PriorityConfirmed(UUID visitId,ClinicalPriority priority,UUID professionalId,Instant decidedAt){}
}
